import { useEffect, useState } from 'react'
import { BookOpen, Trash2, FileText, Sparkles } from 'lucide-react'
import { useFicheStore } from '../../stores/ficheStore'
import { useUIStore } from '../../stores/uiStore'

export function FichePanel(): React.JSX.Element {
  const { fiches, loadFiches, deleteFiche } = useFicheStore()
  const openFilePreview = useUIStore((s) => s.openFilePreview)
  const addToast = useUIStore((s) => s.addToast)
  const [confirming, setConfirming] = useState<string | null>(null)

  // Load on mount and refresh periodically so fiches generated by the agent
  // appear without needing a manual refresh.
  useEffect(() => {
    loadFiches()
    const id = setInterval(loadFiches, 5000)
    return () => clearInterval(id)
  }, [loadFiches])

  async function handleDelete(path: string, subject: string): Promise<void> {
    if (confirming !== path) {
      setConfirming(path)
      setTimeout(() => setConfirming((c) => (c === path ? null : c)), 3000)
      return
    }
    setConfirming(null)
    await deleteFiche(path)
    addToast(`Fiche "${subject}" supprimée`, 'info')
  }

  return (
    <div className="flex flex-col border-b border-cortx-border">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-2.5 bg-cortx-elevated/30">
        <div className="flex items-center gap-2">
          <BookOpen size={14} className="text-cortx-accent" />
          <h3 className="text-xs font-semibold text-cortx-text-primary uppercase tracking-wide">
            Fiches générées
          </h3>
          {fiches.length > 0 && (
            <span className="text-2xs px-1.5 py-0.5 rounded bg-cortx-accent/15 text-cortx-accent font-mono">
              {fiches.length}
            </span>
          )}
        </div>
      </div>

      {/* List */}
      <div className="max-h-[42vh] overflow-y-auto">
        {fiches.length === 0 ? (
          <div className="px-4 py-6 text-center">
            <Sparkles size={18} className="mx-auto mb-2 text-cortx-text-secondary/40" />
            <p className="text-2xs text-cortx-text-secondary/60 leading-relaxed">
              Aucune fiche pour le moment.<br />
              Tape <span className="font-mono text-cortx-accent">/brief sujet</span> pour en générer une.
            </p>
          </div>
        ) : (
          <ul className="divide-y divide-cortx-border/40">
            {fiches.map((fiche) => {
              const isConfirming = confirming === fiche.path
              return (
                <li
                  key={fiche.path}
                  className="group relative px-3 py-2.5 hover:bg-cortx-elevated/40 transition-colors"
                >
                  <button
                    onClick={() => openFilePreview(fiche.path)}
                    className="w-full text-left cursor-pointer"
                    title="Ouvrir dans l'aperçu"
                  >
                    <div className="flex items-start gap-2">
                      <FileText size={12} className="text-cortx-accent mt-0.5 flex-shrink-0" />
                      <div className="flex-1 min-w-0 pr-7">
                        <div className="flex items-center gap-1.5">
                          <span className="text-xs font-medium text-cortx-text-primary truncate">
                            {fiche.subject}
                          </span>
                          {fiche.kind && fiche.kind !== 'brief' && (
                            <span className="text-2xs px-1 py-0.5 rounded bg-cortx-accent/10 text-cortx-accent flex-shrink-0">
                              {fiche.kind}
                            </span>
                          )}
                        </div>
                        {fiche.excerpt && (
                          <p className="text-2xs text-cortx-text-secondary/70 leading-snug mt-0.5 line-clamp-2">
                            {fiche.excerpt}
                          </p>
                        )}
                        {fiche.created && (
                          <span className="text-2xs text-cortx-text-secondary/40 font-mono mt-1 inline-block">
                            {fiche.created}
                          </span>
                        )}
                      </div>
                    </div>
                  </button>
                  <button
                    onClick={(e) => {
                      e.stopPropagation()
                      void handleDelete(fiche.path, fiche.subject)
                    }}
                    className={`absolute top-2.5 right-2 p-1 rounded transition-all cursor-pointer ${
                      isConfirming
                        ? 'bg-cortx-error/20 text-cortx-error opacity-100'
                        : 'opacity-0 group-hover:opacity-100 text-cortx-text-secondary/40 hover:text-cortx-error hover:bg-cortx-error/10'
                    }`}
                    title={isConfirming ? 'Cliquer à nouveau pour confirmer' : 'Supprimer'}
                  >
                    <Trash2 size={11} />
                  </button>
                </li>
              )
            })}
          </ul>
        )}
      </div>
    </div>
  )
}
